=== daggerhart/eventbrite-php-api/tests/assets/TicketBuyerSettings/getEventsTicketBuyerSetting-httpTransaction-200-messageBodySchema.json
{
    "$schema": "http:\/\/json-schema.org\/draft-07\/schema#",
    "type": "object",
    "properties": {
        "confirmation_message": {
            "type": "object",
            "properties": {
                "html": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "instructions": {
            "type": "object",
            "properties": {
                "html": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "event_id": {
            "type": "string"
        },
        "refund_request_enabled": {
            "type": "boolean"
        },
        "redirect_url": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "type": "string"
                }
            ]
        },
        "sales_ended_message": {
            "type": "object",
            "properties": {
                "html": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "allow_attendee_update": {
            "type": "boolean"
        },
        "survey_name": {
            "type": "string"
        },
        "survey_info": {
            "type": "object",
            "properties": {
                "html": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "survey_time_limit": {
            "type": "number"
        },
        "survey_respondent": {
            "enum": [
                "ticket_buyer",
                "attendee"
            ]
        },
        "survey_ticket_classes": {
            "type": "array"
        }
    },
    "meta": {
        "folder": "TicketBuyerSettings",
        "filename": "getEventsTicketBuyerSetting",
        "resourceName": "Retrieve",
        "transition": "Retrieve Ticket Buyer Settings by Event",
        "transitionResponseTypes": {
            "200": "\\Eventbrite\\Model\\DataType\\TicketBuyerSettings",
            "400": "\\Eventbrite\\Model\\DataType\\Error",
            "403": "\\Eventbrite\\Model\\DataType\\Error",
            "404": "\\Eventbrite\\Model\\DataType\\Error"
        },
        "transaction": "httpTransaction",
        "messageType": "httpResponse",
        "resourceGroupName": "TicketBuyerSettings",
        "resourceGroup": "\\Eventbrite\\Resource\\TicketBuyerSettings",
        "transactionMethodName": "getEventsTicketBuyerSetting",
        "responseStatusCode": 200,
        "responseType": "\\Eventbrite\\Model\\DataType\\TicketBuyerSettings"
    }
}

=== daggerhart/eventbrite-php-api/tests/assets/TicketBuyerSettings/updateEventsTicketBuyerSetting-httpTransaction-200-messageBody.json
{
    "confirmation_message": {
        "html": "<H1>Confirmation Message<\/H1>",
        "text": "Confirmation Message"
    },
    "instructions": {
        "html": "<H1>Instructions<\/H1>",
        "text": "Instructions"
    },
    "event_id": "43253626762",
    "refund_request_enabled": true,
    "redirect_url": null,
    "sales_ended_message": {
        "html": "<H1>Sales Ended Message<\/H1>",
        "text": "Sales Ended Message"
    },
    "allow_attendee_update": true,
    "survey_name": "Registration Page",
    "survey_info": {
        "html": "<b>Filling in this survey is required to attend the event<\/b>",
        "text": "Filling in this survey is required to attend the event"
    },
    "survey_time_limit": 15,
    "survey_respondent": "ticket_buyer",
    "survey_ticket_classes": []
}
