=== daggerhart/eventbrite-php-api/tests/assets/StructuredContents/getEventsStructuredContent-httpTransaction-200-messageBodySchema.json
{
    "$schema": "http:\/\/json-schema.org\/draft-07\/schema#",
    "type": "object",
    "properties": {
        "access_type": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "enum": [
                        "private",
                        "public"
                    ]
                }
            ]
        },
        "modules": {
            "type": "array"
        },
        "page_version_number": {
            "type": "string"
        },
        "pagination": {
            "type": "object",
            "properties": {
                "object_count": {
                    "type": "number"
                },
                "page_number": {
                    "type": "number"
                },
                "page_size": {
                    "type": "number"
                },
                "page_count": {
                    "type": "number"
                },
                "continuation": {
                    "type": "string"
                },
                "has_more_items": {
                    "type": "boolean"
                }
            }
        },
        "purpose": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "enum": [
                        "listing",
                        "digital_content"
                    ]
                }
            ]
        },
        "resource_uris": {
            "type": "object",
            "properties": {
                "add_module": {
                    "type": "string"
                },
                "preview_module": {
                    "type": "string"
                },
                "publish": {
                    "type": "string"
                },
                "self": {
                    "type": "string"
                }
            }
        }
    },
    "meta": {
        "folder": "StructuredContents",
        "filename": "getEventsStructuredContent",
        "resourceName": "Retrieve",
        "transition": "Retrieve Latest Published Version of Structured Content by Event Id",
        "transitionResponseTypes": {
            "200": "\\Eventbrite\\Model\\DataType\\StructuredContentPage",
            "400": "\\Eventbrite\\Model\\ModelBase"
        },
        "transaction": "httpTransaction",
        "messageType": "httpResponse",
        "resourceGroupName": "StructuredContents",
        "resourceGroup": "\\Eventbrite\\Resource\\StructuredContents",
        "transactionMethodName": "getEventsStructuredContent",
        "responseStatusCode": 200,
        "responseType": "\\Eventbrite\\Model\\DataType\\StructuredContentPage"
    }
}

=== daggerhart/eventbrite-php-api/tests/assets/StructuredContents/postEventStructuredContent-httpTransaction-200-messageBody.json
{
    "access_type": "private",
    "modules": [
        {
            "id": "",
            "data": {
                "body": {
                    "alignment": "left",
                    "text": ""
                }
            },
            "layout": "image_left",
            "timed_display": {
                "absolute_start_utc": "",
                "absolute_end_utc": "",
                "relative_start (number) - Minutes to which a module is relatively shown. Either absolute_start_utc\/absolute_end_utc OR relative_start\/relative_end should be provided": "",
                "relative_end (number) - Minutes to which a module is relatively hidden. Optional - if relative_end is provided, then relative_start must be provided with it.": ""
            },
            "resource_uris": [],
            "semantic_purpose": "",
            "type": "text"
        },
        {
            "id": "",
            "data": {
                "image": {
                    "image_id": "",
                    "display_size": "small",
                    "corner_style": "rounded",
                    "alt": ""
                },
                "caption": {
                    "body": {
                        "alignment": "left",
                        "text": ""
                    }
                },
                "id": ""
            },
            "layout": "image_left",
            "timed_display": {
                "absolute_start_utc": "",
                "absolute_end_utc": "",
                "relative_start (number) - Minutes to which a module is relatively shown. Either absolute_start_utc\/absolute_end_utc OR relative_start\/relative_end should be provided": "",
                "relative_end (number) - Minutes to which a module is relatively hidden. Optional - if relative_end is provided, then relative_start must be provided with it.": ""
            },
            "resource_uris": [],
            "semantic_purpose": "",
            "type": "image"
        },
        {
            "id": "",
            "data": {
                "video": {
                    "display_size": "",
                    "embed_url": "",
                    "thumbnail_url": "",
                    "url": ""
                },
                "caption": {
                    "body": {
                        "alignment": "left",
                        "text": ""
                    }
                }
            },
            "layout": "image_left",
            "timed_display": {
                "absolute_start_utc": "",
                "absolute_end_utc": "",
                "relative_start (number) - Minutes to which a module is relatively shown. Either absolute_start_utc\/absolute_end_utc OR relative_start\/relative_end should be provided": "",
                "relative_end (number) - Minutes to which a module is relatively hidden. Optional - if relative_end is provided, then relative_start must be provided with it.": ""
            },
            "resource_uris": [],
            "semantic_purpose": "",
            "type": "video"
        }
    ],
    "page_version_number": "",
    "pagination": {
        "object_count": 1,
        "page_number": 1,
        "page_size": 1,
        "page_count": 1,
        "continuation": "dGhpcyBpcyBhIGNvbnRpbnVhdGlvbiB0b2tlbg",
        "has_more_items": false
    },
    "purpose": "listing",
    "resource_uris": {
        "add_module": "",
        "preview_module": "",
        "publish": "",
        "self": ""
    }
}
