=== daggerhart/eventbrite-php-api/tests/assets/Questions/createEventsCannedQuestion-httpTransaction-200-messageBodySchema.json
{
    "$schema": "http:\/\/json-schema.org\/draft-07\/schema#",
    "type": "object",
    "properties": {
        "resource_uri": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "question": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string"
                },
                "html": {
                    "type": "string"
                }
            }
        },
        "type": {
            "type": "string"
        },
        "required": {
            "type": "boolean"
        },
        "include": {
            "type": "boolean"
        },
        "editable": {
            "type": "boolean"
        },
        "choices": {
            "type": "array"
        },
        "ticket_classes": {
            "type": "array"
        },
        "group_id": {
            "type": "string"
        },
        "group_display_header": {
            "type": "string"
        },
        "respondent": {
            "type": "string"
        },
        "default_value": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "type": "string"
                }
            ]
        }
    },
    "meta": {
        "folder": "Questions",
        "filename": "createEventsCannedQuestion",
        "resourceName": "Create Default Question",
        "transition": "Create a Default Question for an Event",
        "transitionResponseTypes": {
            "200": "\\Eventbrite\\Model\\DataType\\CannedQuestion",
            "400": "\\Eventbrite\\Model\\DataType\\Error"
        },
        "transaction": "httpTransaction",
        "messageType": "httpResponse",
        "resourceGroupName": "Questions",
        "resourceGroup": "\\Eventbrite\\Resource\\Questions",
        "transactionMethodName": "createEventsCannedQuestion",
        "responseStatusCode": 200,
        "responseType": "\\Eventbrite\\Model\\DataType\\CannedQuestion"
    }
}

=== daggerhart/eventbrite-php-api/tests/assets/Questions/postEventCannedQuestions-httpTransaction-200-messageBody.json
{
    "resource_uri": "https:\/\/www.eventbriteapi.com\/v3\/events\/12345\/canned_questions\/job_title\/",
    "id": "job_title",
    "question": {
        "text": "Job Title",
        "html": "Job Title"
    },
    "type": "text",
    "required": false,
    "include": true,
    "editable": true,
    "choices": [],
    "ticket_classes": [],
    "group_id": "work_information",
    "group_display_header": "Work Info",
    "respondent": "ticket_buyer",
    "default_value": null
}
