=== daggerhart/eventbrite-php-api/tests/assets/Questions/getEventsQuestions-httpTransaction-200-messageBodySchema.json
{
    "$schema": "http:\/\/json-schema.org\/draft-07\/schema#",
    "type": "object",
    "properties": {
        "resource_uri": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "question": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string"
                },
                "html": {
                    "type": "string"
                }
            }
        },
        "required": {
            "type": "boolean"
        },
        "display_answer_on_order": {
            "type": "boolean"
        },
        "type": {
            "enum": [
                "checkbox",
                "dropdown",
                "text",
                "paragraph",
                "radio",
                "waiver"
            ]
        },
        "respondent": {
            "enum": [
                "ticket_buyer",
                "attendee"
            ]
        },
        "waiver": {
            "type": "string"
        },
        "choices": {
            "type": "array"
        },
        "ticket_classes": {
            "type": "array"
        },
        "parent_id": {
            "type": "string"
        },
        "parent_choice_id": {
            "type": "string"
        },
        "sorting": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "type": "number"
                }
            ]
        }
    },
    "meta": {
        "folder": "Questions",
        "filename": "getEventsQuestions",
        "resourceName": "Get Custom Question by Id",
        "transition": "Get Custom Question by Id",
        "transitionResponseTypes": {
            "200": "\\Eventbrite\\Model\\DataType\\BaseQuestion",
            "404": "\\Eventbrite\\Model\\ModelBase"
        },
        "transaction": "httpTransaction",
        "messageType": "httpResponse",
        "resourceGroupName": "Questions",
        "resourceGroup": "\\Eventbrite\\Resource\\Questions",
        "transactionMethodName": "getEventsQuestions",
        "responseStatusCode": 200,
        "responseType": "\\Eventbrite\\Model\\DataType\\BaseQuestion"
    }
}

=== daggerhart/eventbrite-php-api/tests/assets/Questions/createEventsQuestions-httpTransaction-200-messageBody.json
{
    "resource_uri": "https:\/\/www.eventbriteapi.com\/v3\/events\/12345\/questions\/123456789\/",
    "id": "123456789",
    "question": {
        "text": "Custom Question Title",
        "html": "Question Title"
    },
    "required": true,
    "display_answer_on_order": true,
    "type": "checkbox",
    "respondent": "ticket_buyer",
    "choices": [
        {
            "answer": {
                "text": "Choice 1",
                "html": "Choice 1"
            },
            "quantity_available": 250,
            "quantity_sold": 5,
            "low_stock": 250,
            "id": "123456",
            "subquestion_ids": []
        }
    ],
    "ticket_classes": [
        {
            "id": "1234",
            "name": "Ticket class name"
        }
    ],
    "parent_id": "24038723",
    "parent_choice_id": "66915463",
    "sorting": 5
}
