=== daggerhart/eventbrite-php-api/tests/assets/EventCapacities/postEventCapacityTier-httpTransaction-200-messageBodySchema.json
{
    "$schema": "http:\/\/json-schema.org\/draft-07\/schema#",
    "type": "object",
    "properties": {
        "event_id": {
            "type": "string"
        },
        "quantity_pending": {
            "type": "number"
        },
        "quantity_sold": {
            "type": "number"
        },
        "quantity_total": {
            "type": "number"
        },
        "capacity_pending": {
            "type": "number"
        },
        "capacity_sold": {
            "type": "number"
        },
        "capacity_total": {
            "type": "number"
        },
        "capacity_is_custom": {
            "type": "boolean"
        },
        "holds": {
            "type": "array"
        }
    },
    "meta": {
        "folder": "EventCapacities",
        "filename": "postEventCapacityTier",
        "resourceName": "Update",
        "transition": "Update a Capacity Tier",
        "transitionResponseTypes": {
            "200": "\\Eventbrite\\Model\\DataType\\CapacityTier",
            "400": "\\Eventbrite\\Model\\DataType\\Error",
            "403": "\\Eventbrite\\Model\\DataType\\Error",
            "404": "\\Eventbrite\\Model\\DataType\\Error"
        },
        "transaction": "httpTransaction",
        "messageType": "httpResponse",
        "resourceGroupName": "EventCapacities",
        "resourceGroup": "\\Eventbrite\\Resource\\EventCapacities",
        "transactionMethodName": "postEventCapacityTier",
        "responseStatusCode": 200,
        "responseType": "\\Eventbrite\\Model\\DataType\\CapacityTier"
    }
}

=== daggerhart/eventbrite-php-api/tests/assets/EventCapacities/postEventCapacityTier-httpTransaction-200-messageBody.json
{
    "event_id": "5678",
    "quantity_pending": 2,
    "quantity_sold": 10,
    "quantity_total": 30,
    "capacity_pending": 10,
    "capacity_sold": 20,
    "capacity_total": 100,
    "capacity_is_custom": true,
    "holds": [
        {
            "id": "I1234",
            "event_id": "5678",
            "name": "Marketing",
            "abbreviation": "MKT",
            "sort_order": 1,
            "color": "#fac114",
            "quantity_sold": 10,
            "quantity_total": 30,
            "quantity_pending": 5
        }
    ]
}
