=== daggerhart/eventbrite-php-api/tests/assets/EventTeams/getEventTeam-httpTransaction-200-messageBodySchema.json
{
    "$schema": "http:\/\/json-schema.org\/draft-07\/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "creator": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "emails": {
                    "type": "array"
                }
            }
        },
        "changed": {
            "type": "string"
        },
        "created": {
            "type": "string"
        },
        "attendee_count": {
            "type": "number"
        },
        "token": {
            "type": "string"
        },
        "event_id": {
            "type": "string"
        },
        "date_joined": {
            "type": "string"
        }
    },
    "meta": {
        "folder": "EventTeams",
        "filename": "getEventTeam",
        "resourceName": "Retrieve",
        "transition": "Retrieve Team",
        "transitionResponseTypes": {
            "200": "\\Eventbrite\\Model\\DataType\\EventTeamResponse"
        },
        "transaction": "httpTransaction",
        "messageType": "httpResponse",
        "resourceGroupName": "EventTeams",
        "resourceGroup": "\\Eventbrite\\Resource\\EventTeams",
        "transactionMethodName": "getEventTeam",
        "responseStatusCode": 200,
        "responseType": "\\Eventbrite\\Model\\DataType\\EventTeamResponse"
    }
}

=== daggerhart/eventbrite-php-api/tests/assets/EventTeams/getEventsTeams-httpTransaction-200-messageBody.json
{
    "id": "1",
    "name": "Testing",
    "creator": {
        "id": "272057970621",
        "name": "john@example.com",
        "emails": [
            {
                "verified": false,
                "primary": true,
                "email": "john@example.com"
            }
        ]
    },
    "changed": "2018-10-22T21:43:16Z",
    "created": "2018-10-22T21:43:16Z",
    "attendee_count": 2,
    "token": "",
    "event_id": "12345",
    "date_joined": ""
}
