=== daggerhart/eventbrite-php-api/tests/assets/Webhooks/postOrganizationWebhooks-httpTransaction-200-messageBodySchema.json
{
    "$schema": "http:\/\/json-schema.org\/draft-07\/schema#",
    "type": "object",
    "properties": {
        "endpoint_url": {
            "type": "string"
        },
        "actions": {
            "type": "array"
        },
        "event_id": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "resource_uri": {
            "type": "string"
        },
        "created": {
            "type": "string"
        },
        "user_id": {
            "type": "string"
        }
    },
    "required": [
        "endpoint_url"
    ],
    "meta": {
        "folder": "Webhooks",
        "filename": "postOrganizationWebhooks",
        "resourceName": "Create",
        "transition": "Create Webhooks by Organization ID",
        "transitionResponseTypes": {
            "200": "\\Eventbrite\\Model\\DataType\\Webhook"
        },
        "transaction": "httpTransaction",
        "messageType": "httpResponse",
        "resourceGroupName": "Webhooks",
        "resourceGroup": "\\Eventbrite\\Resource\\Webhooks",
        "transactionMethodName": "postOrganizationWebhooks",
        "responseStatusCode": 200,
        "responseType": "\\Eventbrite\\Model\\DataType\\Webhook"
    }
}

=== daggerhart/eventbrite-php-api/tests/assets/Webhooks/createOrganizationsWebhook-httpTransaction-200-messageBody.json
{
    "endpoint_url": "https:\/\/c3e123a02a37497897e08927816bb0c920c9de23c77804f.example.com",
    "actions": [
        "event.created",
        "event.published",
        "order.placed"
    ],
    "event_id": "62541733007",
    "id": "2006536",
    "resource_uri": "https:\/\/www.eventbriteapi.com\/v3\/webhooks\/1990496\/",
    "created": "2020-03-03T18:09:37Z",
    "user_id": "308733706151"
}
