=== daggerhart/eventbrite-php-api/tests/assets/Venues/getVenue-httpTransaction-200-messageBodySchema.json
{
    "$schema": "http:\/\/json-schema.org\/draft-07\/schema#",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "age_restriction": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "type": "string"
                }
            ]
        },
        "capacity": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "type": "number"
                }
            ]
        },
        "address": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "type": "object",
                    "properties": {
                        "address_1": {
                            "anyOf": [
                                {
                                    "type": "null"
                                },
                                {
                                    "type": "string"
                                }
                            ]
                        },
                        "address_2": {
                            "anyOf": [
                                {
                                    "type": "null"
                                },
                                {
                                    "type": "string"
                                }
                            ]
                        },
                        "city": {
                            "anyOf": [
                                {
                                    "type": "null"
                                },
                                {
                                    "type": "string"
                                }
                            ]
                        },
                        "region": {
                            "anyOf": [
                                {
                                    "type": "null"
                                },
                                {
                                    "type": "string"
                                }
                            ]
                        },
                        "postal_code": {
                            "anyOf": [
                                {
                                    "type": "null"
                                },
                                {
                                    "type": "string"
                                }
                            ]
                        },
                        "country": {
                            "anyOf": [
                                {
                                    "type": "null"
                                },
                                {
                                    "type": "string"
                                }
                            ]
                        },
                        "latitude": {
                            "anyOf": [
                                {
                                    "type": "null"
                                },
                                {
                                    "type": "string"
                                }
                            ]
                        },
                        "longitude": {
                            "anyOf": [
                                {
                                    "type": "null"
                                },
                                {
                                    "type": "string"
                                }
                            ]
                        }
                    }
                }
            ]
        },
        "resource_uri": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "latitude": {
            "type": "string"
        },
        "longitude": {
            "type": "string"
        }
    },
    "required": [
        "name"
    ],
    "meta": {
        "folder": "Venues",
        "filename": "getVenue",
        "resourceName": "Retrieve",
        "transition": "Retrieve a Venue",
        "transitionResponseTypes": {
            "200": "\\Eventbrite\\Model\\DataType\\VenueResponse"
        },
        "transaction": "httpTransaction",
        "messageType": "httpResponse",
        "resourceGroupName": "Venues",
        "resourceGroup": "\\Eventbrite\\Resource\\Venues",
        "transactionMethodName": "getVenue",
        "responseStatusCode": 200,
        "responseType": "\\Eventbrite\\Model\\DataType\\VenueResponse"
    }
}

=== daggerhart/eventbrite-php-api/tests/assets/Venues/getVenue-httpTransaction-200-messageBody.json
{
    "name": "Great Venue",
    "age_restriction": null,
    "capacity": 100,
    "address": {
        "address_1": null,
        "address_2": null,
        "city": null,
        "region": null,
        "postal_code": null,
        "country": null,
        "latitude": null,
        "longitude": null
    },
    "resource_uri": "https:\/\/www.eventbriteapi.com\/v3\/venues\/3003\/",
    "id": "3003",
    "latitude": "49.28497549999999",
    "longitude": "123.11082529999999"
}
